name: EcoDeploy CI

on: [push]

jobs:
  carbon-aware-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run EcoDeploy
      id: ecodeploy
      run: |
        echo "Determining optimal region..."
        python run_ecodeploy.py
        echo "region=$(cat region.txt)" >> $GITHUB_OUTPUT
      env:
        ELECTRICITY_MAP_TOKEN: ${{ secrets.ELECTRICITY_MAP_TOKEN }}
        
    - name: Deploy to selected region
      run: |
        echo "Deploying to ${{ steps.ecodeploy.outputs.region }}"
        # Add your actual deployment commands here
        # Example: 
        # aws s3 sync build/ s3://my-bucket-${{ steps.ecodeploy.outputs.region }}/